# Generated by Django 5.1.6 on 2025-02-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giocatore',
            name='ruolo',
            field=models.CharField(choices=[('Portiere', 'Portiere'), ('Difensore', 'Difensore'), ('Centrocampista', 'Centrocampista'), ('Attaccante', 'Attaccante')], max_length=20),
        ),
    ]
