# Generated by Django 5.1.6 on 2025-02-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_squadre_serie_a_squadre_serie_b_squadre_serie_c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giocatore',
            name='id_squadra_serie_A',
            field=models.ManyToManyField(blank=True, related_name='Seria_A', to='api.squadre_serie_a'),
        ),
        migrations.AlterField(
            model_name='giocatore',
            name='id_squadra_serie_B',
            field=models.ManyToManyField(blank=True, related_name='Seria_B', to='api.squadre_serie_b'),
        ),
        migrations.AlterField(
            model_name='giocatore',
            name='id_squadra_serie_C',
            field=models.ManyToManyField(blank=True, related_name='Seria_C', to='api.squadre_serie_c'),
        ),
    ]
