# Generated by Django 5.1.6 on 2025-02-12 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_giocatore_id_squadra_serie_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giocatore',
            name='id_squadra_serie_A',
        ),
        migrations.AddField(
            model_name='giocatore',
            name='id_squadra_serie_A',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Seria_A', to='api.squadre_serie_a'),
        ),
    ]
