# Generated by Django 5.1.6 on 2025-02-25 12:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_squadre_serie_a_user_alter_squadre_serie_a_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadre_serie_a',
            name='mercato',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
    ]
