# Generated by Django 5.1.6 on 2025-02-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_squadre_serie_a_mercato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squadre_serie_a',
            name='mercato',
            field=models.JSONField(default=list),
        ),
    ]
